---
title: "Antigen Tracking Figures"
author: "Ryan Sheridan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc:            true
    toc_float:      true
    toc_depth:      4
    df_print:       "paged"
    code_folding:   "hide"
    self_contained: true
    highlight:      "kate"
params:
  template_dir:    "src"                                                                  # Rmd templates
  so_dir:          "~/Dropbox/Ryan/Projects/antigen-exchange/results/sobjs/2024-07-01"    # Seurat objects
  xen_dir:         "~/Dropbox/Ryan/Projects/antigen-exchange/results/xenium/2024-03-22"   # Xenium objects
  geo_dir:         "results/geo"                                                          # GEO submission files
  sample_info:     "sample_info.xlsx"                                                     # samples names/info
  xen_res_dir: "results/xenium/20240322__194506__032224_Tamburini_Run_1"                     # Directory with Xenium data
  xen_regex:   ["output-XETG00230__0022624__[A-Z]__", "output-XETG00230__0022841__[A-Z]__"]  # Regex to pull samples for Xenium slides
  xen_samples: 
    value:
      A: ["6wk", 1, 2]      # Sample identity and 6wk and 3wk barcode identity (in this order)
      B: ["6wk", 2, 1]      # e.g. `1` indicates GeoMx-Barcode01
      C: ["6wk-3wk", 1, 2]
      D: ["6wk-3wk", 2, 1]
      E: ["3wk", 2, 1]
      F: ["3wk", 1, 2]
  xen_ag_targets:
    value:
      Ag_tag_1: "GeoMx-Barcode01-ERCC00142"
      Ag_tag_2: "GeoMx-Barcode02-ERCC00144"
  xen_custom_targets: "ref/QX42XM_mMulti_98g_custom_sequences.csv" # Custom non-endogenous targets in panel
---

---

```{r "setup", include = FALSE}
# Default chunk options
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo    = FALSE,
  dpi     = 300
)

# Set python environment
reticulate::use_condaenv("umap", conda = "~/.local/bin/micromamba")

GiottoClass::set_giotto_python_path("umap")

# Main setup
knitr::knit(here::here(params$template_dir, "setup.Rmd"), "")

# Plot parameters
min_cells <- 5
rf_typs   <- c("cLEC", "fLEC", "Collecting")
rf_tms    <- c(14, 21, 42)

ag_modules <- rf_typs %>%
  map(str_c, c("_high", "_low")) %>%
  unlist()

# Keys for naming labels
ag_clmns <- c("Ag_3wk_score", "Ag_6wk_score")

ag_labs_2 <- set_names(
  c("Ag-score\n21 day", "Ag-score\n42 day"),
  ag_clmns
)

ag_labs <- ag_labs_2 %>%
  str_replace_all("\n", " (") %>%
  str_replace_all("$", ")") %>%
  set_names(ag_clmns)

# Mouse key
m_key <- c(
  d2        = "2 day",
  d14       = "14 day",
  `3wk`     = "21 day",
  `6wk`     = "42 day",
  `6wk-3wk` = "dual"
)
```

```{r "load xenium data", include = FALSE}
# Xenium setup
xen_slides <- seq_along(params$xen_regex)

chunks <- xen_slides %>%
  map_chr(~ knit_expand(here(params$template_dir, "setup-xenium.Rmd")))

knit(text = chunks, output = "")

# Key Xenium marker genes
xen_gns <- c(
  "Ptprc",
  "Cd3d", "Cd19",
  "Cd8a",
  "Prox1", "Lyve1",
  "Pdpn", "Pecam1",
  "Itgam",  # cDC2
  "Itgax",  # DCs
  "Zbtb46", # DCs
  "Sirpa",
  "Xcr1",
  "Siglech",
  "Tbx21"
)

# Load Xenium data
xen <- xen_slides %>%
  map(~ {
    here(params$xen_dir, str_c("xen_s", .x, ".qs")) %>%
      qread() %>%
      FetchData(c(colnames(.@meta.data), xen_gns)) %>%
      as_tibble(rownames = "cell_id") %>%
      mutate(slide = .x)
  }) %>%
  bind_rows() %>%
  mutate(
    cell_type = if_else(grepl("^other", cell_type), "unassigned", cell_type),
    cell_type = if_else(
      cell_type %in% c("Macrophages", "Monocytes"),
      "Mon/Mac",
      cell_type
    )
  )

# Top cell types to plot
dcs <- xen$cell_type %>%
  unique() %>%
  grep("DC", ., value = TRUE) %>%
  sort()

ag_dcs <- xen %>%
  filter(cell_type %in% dcs) %>%
  group_by(cell_type) %>%
  filter(all(table(Ag_class) > 15)) %>%
  pull(cell_type) %>%
  unique()

top_types <- c("LEC", dcs)

# FOVs to plot
fovs    <- sort(unique(xen$fov))
top_fov <- "D"
bad_fov <- "C"  # section from very end of LN

# Format plotting data
xen_ag_classes <- c(
  `Ag-low`  = "Ag-",
  `Ag-high` = "Ag+"
)

xen <- xen %>%
  mutate(
    Ag_class = recode(Ag_class, !!!xen_ag_classes),
    Ag_class = fct_relevel(Ag_class, unname(xen_ag_classes)),
    slide    = str_c("section ", slide)
  ) %>%
  arrange(Ag_class)
```

```{r "giotto object", eval = FALSE}
# Perform cell proximity analysis for section D
prox_res <- params$xen_regex %>%
  imap(~ {
    xen_dirs <- dir(
      here(params$xen_res_dir),
      pattern    = .x,
      full.names = TRUE
    )
    
    names(xen_dirs) <- xen_dirs %>%
      str_extract("(?<=__)[A-Z](?=__)")
    
    # Create Giotto object
    # * store custom targets as separate assay
    meta <- xen %>%
      filter(
        slide == str_c("section ", .y),
        fov   == top_fov
      ) %>%
      select(cell_ID = cell_id, cell_type, Ag_class) %>%
      mutate(
        cell_type = str_c(cell_type, " (", Ag_class, ")"),
        cell_ID   = str_remove(cell_ID, "^[A-Z]_")
      ) %>%
      select(-Ag_class) %>%
      readCellMetadata()
    
    obj <- xen_dirs[[top_fov]] %>%
      createGiottoXeniumObject() %>%
      setCellMetadata(meta)
    
    # Spatial network
    obj <- obj %>%
      createSpatialDelaunayNetwork(
        spat_unit = "cell",
        feat_type = "rna"
      )
    
    obj %>%
      qsave(here(str_c("results/gio_s", .y, ".qs")))
      
    # Spatial correlation
    prox <- obj %>%
      cellProximityEnrichment(
        spat_unit      = "cell",
        feat_type      = "rna",
        cluster_column = "cell_type"
      )
    
    prox %>%
      qsave(here(str_c("results/prox_s", .y, ".qs")))
    
    prox
  })

# Save proximity enrichment results
prox_df <- prox_res %>%
  imap_dfr(~ {
    .x$enrichm_res %>%
      as_tibble() %>%
      mutate(slide = str_c("section ", .y))
  })

prox_df %>%
  write_tsv(here("results/prox.tsv.gz"))
```

---

<br>

<br>

## Session info

```{r "session info"}
sessionInfo()
```
